shows:
  - feed-url: "https://www.zdf.de/rss/zdf/comedy/zdf-magazin-royale"
    filter:
      regex: "zdf-magazin-royale-vom-\\d"
      regexField: "link"
      minDate: "2021-09-01 00:00+00:00"
    download:
      folder: "/serien/ZDF Magazin Royale"
      filename: "ZDF Magazin Royale"
interval: 60
