name: Quality
on:
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Scan SonarQube
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}